export const sampleData = [
    {
        id: "Dqegxfcht0N6JbtYXlJm",
        name: "Šviežia viščiukų broilerių filė IKI MĖSA, 500 g",
        categoryId: "yNobk8Iq0oUmYo88MItC",
        price: 4.99,
        url: "https://lastmile.lt/product/IKI/Sviezia-visciuku-broileriu-file-IKI-MESA-500-g",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2Fglobal_Dqegxfcht0N6JbtYXlJm_xGdb10o0VzY1SFD6eDjbpqgxmW02_AZM6kYcgKkoAnoB4xGbn_thumb.jpg?generation=1647862190106750&alt=media",
        pricePer: 9.98,
        unit: "kg",
        shop: "iki",
        available: true,
    },
    {
        id: "G4X4szvpHhdpbR9SXPUQ",
        name: "Glaistytas sūrelis MAGIJA su vanile, 24% rieb., 45 g",
        categoryId: "DWDGJLEUeALikCN2z1hO",
        price: 0.59,
        url: "https://lastmile.lt/product/IKI/Glaistytas-surelis-MAGIJA-su-vanile-24percent-rieb-45-g",
        image: "https://firebasestorage.googleapis.com/v0/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2FthumbUrl%2FCvKfTzV4TN5U8BTMF1Hl_10015_W5RvAbpnRicygag1V4nopPhtD8z2_nPPsSl5dXjttnq0gTxcg.webp?alt=media&token=69f47b22-1e2d-4e57-a030-355814c8d8e9",
        pricePer: 13.11,
        unit: "kg",
        shop: "iki",
        available: true,
    },
    {
        id: "259143",
        name: "Žurnalas STILIUS",
        categoryId: "WRQDAv6Wq0NOFwiWLdKY",
        price: 1.9,
        url: "https://lastmile.lt/product/IKI/Zurnalas-STILIUS",
        image: "https://firebasestorage.googleapis.com/v0/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2FthumbUrl%2FCvKfTzV4TN5U8BTMF1Hl_259143_W5RvAbpnRicygag1V4nopPhtD8z2_zwbzDaIRMbANly2Mpacl.webp?alt=media&token=5bd1f4e2-43bd-4eaf-b3d3-9bdb04a38f17",
        pricePer: 1.9,
        unit: "vnt",
        shop: "iki",
        available: true,
    },
    {
        id: "277865",
        name: "Žurnalas ŽMONĖS",
        categoryId: "WRQDAv6Wq0NOFwiWLdKY",
        price: 3.99,
        url: "https://lastmile.lt/product/IKI/Zurnalas-ZMONES",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2FCvKfTzV4TN5U8BTMF1Hl_277865_CvKfTzV4TN5U8BTMF1Hl_cTAkEjfDTeMFXf0e6W4JKKhwXXA3_7q9f6W3G8X2SqRhJP3j9_thumb.webp?generation=1698315655409889&alt=media",
        pricePer: 3.99,
        unit: "vnt",
        shop: "iki",
        available: true,
    },
    {
        id: "X6HLfF3VbAsvMi4lPo7z",
        name: "Fermentinis ROKIŠKIO sūris, 45% riebumo, 240 g",
        categoryId: "CdWuu4uUCdxn6AIe4gqc",
        price: 2.59,
        url: "https://lastmile.lt/product/IKI/Fermentinis-ROKISKIO-suris-45percent-riebumo-240-g",
        image: "https://firebasestorage.googleapis.com/v0/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2FthumbUrl%2FCvKfTzV4TN5U8BTMF1Hl_87483_W5RvAbpnRicygag1V4nopPhtD8z2_GrHq1ANH7XeE4cSiTusJ.webp?alt=media&token=993b5d53-5ce8-4b68-9486-34e0863484e4",
        pricePer: 10.79,
        unit: "kg",
        shop: "iki",
        available: true,
    },
    {
        id: "p2NlVbLg7SOuW6UcxEoq",
        name: "Kūčiukai BEATOS VIRTUVĖ, 200 g.",
        categoryId: "r6mhRf9wQKjV9mA7gxdS",
        price: null,
        url: "https://lastmile.lt/product/IKI/Kuciukai-BEATOS-VIRTUVE-200-g.",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2Fglobal_p2NlVbLg7SOuW6UcxEoq_xGdb10o0VzY1SFD6eDjbpqgxmW02_qEGHQ8cZ1zBfcGR9pGxi_thumb.jpg?generation=1669377439859317&alt=media",
        pricePer: null,
        unit: "kg",
        shop: "iki",
        available: false,
    },
    {
        id: "dwHYzca13MDC6xgxc2YW",
        name: "Advento kalendorius MILKA, 90 g",
        categoryId: "r6mhRf9wQKjV9mA7gxdS",
        price: null,
        url: "https://lastmile.lt/product/IKI/Advento-kalendorius-MILKA-200-g",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2FCvKfTzV4TN5U8BTMF1Hl_dwHYzca13MDC6xgxc2YW_CvKfTzV4TN5U8BTMF1Hl_W5RvAbpnRicygag1V4nopPhtD8z2_JcUwetU1Rtg4YV3ojGlf_thumb.webp?generation=1699527949442846&alt=media",
        pricePer: null,
        unit: "kg",
        shop: "iki",
        available: false,
    },
    {
        id: "222201",
        name: "Kalėdinis augalas, PUŠIS",
        categoryId: "6ZTlgDGgZJ3vQkTbrfnp",
        price: null,
        url: "https://lastmile.lt/product/IKI/Kaledinis-augalas-PUSIS",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2FCvKfTzV4TN5U8BTMF1Hl_222201_CvKfTzV4TN5U8BTMF1Hl_W5RvAbpnRicygag1V4nopPhtD8z2_jqXc4E49uHnKdDCQ5tX5_thumb.webp?generation=1701760885256432&alt=media",
        pricePer: null,
        unit: "vnt",
        shop: "iki",
        available: false,
    },
    {
        id: "278337",
        name: "Advento kalendorius EDLE TROPFEN, 300 g",
        categoryId: "r6mhRf9wQKjV9mA7gxdS",
        price: null,
        url: "https://lastmile.lt/product/IKI/Advento-kalendorius-EDLE-TROPFEN-300-g",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2FCvKfTzV4TN5U8BTMF1Hl_278337_CvKfTzV4TN5U8BTMF1Hl_W5RvAbpnRicygag1V4nopPhtD8z2_NEpDg8TczCaDo0qqDsF8_thumb.webp?generation=1699527968510478&alt=media",
        pricePer: null,
        unit: "kg",
        shop: "iki",
        available: false,
    },
    {
        id: "BhTtLh39D1ha1o1kLTtU",
        name: "Pyragas PANETTONE, 750 g",
        categoryId: "r6mhRf9wQKjV9mA7gxdS",
        price: null,
        url: "https://lastmile.lt/product/IKI/Pyragas-PANETTONE-750-g",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2FCvKfTzV4TN5U8BTMF1Hl_BhTtLh39D1ha1o1kLTtU_CvKfTzV4TN5U8BTMF1Hl_W5RvAbpnRicygag1V4nopPhtD8z2_XbUmKAEW87tKb98sdJSz_thumb.webp?generation=1701760908670819&alt=media",
        pricePer: null,
        unit: "kg",
        shop: "iki",
        available: false,
    },
    {
        id: "224751",
        name: "Rinkinys su žaisliuku KINDER MAXI MIX, 133 g",
        categoryId: "O34aqg6jN7ExE0ySDL3j",
        price: null,
        url: "https://lastmile.lt/product/IKI/Rinkinys-su-zaisliuku-KINDER-MAXI-MIX-133-g",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2FCvKfTzV4TN5U8BTMF1Hl_224751_CvKfTzV4TN5U8BTMF1Hl_W5RvAbpnRicygag1V4nopPhtD8z2_V2f737k7uDSDdVJMbfs4_thumb.webp?generation=1699527949938556&alt=media",
        pricePer: null,
        unit: "kg",
        shop: "iki",
        available: false,
    },
    {
        id: "5zGqb4G3vBv3mYnb0D0j",
        name: "Advento kalendorius MILKA Snowman, 236 g",
        categoryId: "r6mhRf9wQKjV9mA7gxdS",
        price: null,
        url: "https://lastmile.lt/product/IKI/Advento-kalendorius-MILKA-Snowman-236-g",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2FCvKfTzV4TN5U8BTMF1Hl_5zGqb4G3vBv3mYnb0D0j_CvKfTzV4TN5U8BTMF1Hl_W5RvAbpnRicygag1V4nopPhtD8z2_Ow4oKfQMXz8ogf2DWWlK_thumb.webp?generation=1699527953621181&alt=media",
        pricePer: null,
        unit: "kg",
        shop: "iki",
        available: false,
    },
    {
        id: "iNqZIWhnRVjabieALQrW",
        name: "Bananai, 1 kg",
        categoryId: "dXm2I2xsSMKPb34maRSX",
        price: 1.39,
        url: "https://lastmile.lt/product/IKI/Bananai-1-kg",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/images%2Fchain_products%2FIKI%2Fthumb_iNqZIWhnRVjabieALQrW.jpg?generation=1654518838165052&alt=media",
        pricePer: 1.39,
        unit: "kg",
        shop: "iki",
        available: true,
    },
    {
        id: "UxLg4tKgD0SK8jEm2gnd",
        name: "Rokiškio NAMINIS sviestas, 82% rieb., 180 g",
        categoryId: "MG3ys0lt7bRcpQQDeOLv",
        price: 2.49,
        url: "https://lastmile.lt/product/IKI/Rokiskio-NAMINIS-sviestas-82percent-rieb-180-g",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2FCvKfTzV4TN5U8BTMF1Hl_UxLg4tKgD0SK8jEm2gnd_xGdb10o0VzY1SFD6eDjbpqgxmW02_at57ZbilfbHCMXqtvBIu_thumb.jpg?generation=1676450890495097&alt=media",
        pricePer: 13.83,
        unit: "kg",
        shop: "iki",
        available: true,
    },
    {
        id: "JlZSxkyfHhbBKrMXHCvC",
        name: "Žurnalas ILIUSTRUOTAS MOKSLAS ŽURNALAS, 1 vnt.",
        categoryId: "WRQDAv6Wq0NOFwiWLdKY",
        price: 5.5,
        url: "https://lastmile.lt/product/IKI/Zurnalas-ILIUSTRUOTAS-MOKSLAS-ZURNALAS-1-vnt",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2FCvKfTzV4TN5U8BTMF1Hl_JlZSxkyfHhbBKrMXHCvC_CvKfTzV4TN5U8BTMF1Hl_cTAkEjfDTeMFXf0e6W4JKKhwXXA3_vk4oN8hvvPWlG8SNQcRK_thumb.webp?generation=1698315584306310&alt=media",
        pricePer: 5.5,
        unit: "vnt",
        shop: "iki",
        available: true,
    },
    {
        id: "YmK0aF7YBef9009hyj4l",
        name: "Avokadai HASS, 500 g",
        categoryId: "vDZoX4YoRHKJp2fiFp0d",
        price: 1.99,
        url: "https://lastmile.lt/product/IKI/Avokadai-HASS-500-g",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/images%2Fproducts%2Fthumb_YmK0aF7YBef9009hyj4l.jpg?generation=1582202027645425&alt=media",
        pricePer: 3.98,
        unit: "kg",
        shop: "iki",
        available: true,
    },
    {
        id: "GPyoNPbPmVKuf0lTwACA",
        name: "Braškės, 400 g",
        categoryId: "8p87CHLyn8ieAGHm1Pay",
        price: 3.99,
        url: "https://lastmile.lt/product/IKI/Braskes-400-g",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2Fglobal_GPyoNPbPmVKuf0lTwACA_xGdb10o0VzY1SFD6eDjbpqgxmW02_MZHajUuI98wYoxudA48B_thumb.jpg?generation=1679554246037003&alt=media",
        pricePer: 9.98,
        unit: "kg",
        shop: "iki",
        available: false,
    },
    {
        id: "281024",
        name: "Balti vištų kiaušiniai, M dydžio, 10 vnt.",
        categoryId: "ewKKA6euD2QXtN8OpYnu",
        price: null,
        url: "https://lastmile.lt/product/IKI/Balti-vistu-kiausiniai-M-dydzio-10-vnt",
        image: "https://firebasestorage.googleapis.com/v0/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2FthumbUrl%2FCvKfTzV4TN5U8BTMF1Hl_281024_W5RvAbpnRicygag1V4nopPhtD8z2_cOvdUer9cR9RIdYCoNsH.webp?alt=media&token=e07bcd1a-6673-4965-91bc-c7aae608f2b8",
        pricePer: null,
        unit: "vnt",
        shop: "iki",
        available: false,
    },
    {
        id: "GRiBFOyfPCSIUCn9NLHM",
        name: "Lietuviški ilgavaisiai agurkai, 1 vnt.",
        categoryId: "ofL9nIXiarQ8oBAJeczM",
        price: 1.49,
        url: "https://lastmile.lt/product/IKI/Lietuviski-ilgavaisiai-agurkai-1-vnt",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2Fglobal_GRiBFOyfPCSIUCn9NLHM_W5RvAbpnRicygag1V4nopPhtD8z2_w3UjMbzk0bxA3YdbtnK6_thumb.jpg?generation=1683626302271763&alt=media",
        pricePer: 1.49,
        unit: "vnt",
        shop: "iki",
        available: true,
    },
    {
        id: "0SFs93BQwFn5k23gDvll",
        name: "Plautos morkos CLEVER",
        categoryId: "Tf2kE5ysa0DAQrkKLQz9",
        price: 0.99,
        url: "https://lastmile.lt/product/IKI/Plautos-morkos-CLEVER",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/images%2Fproducts%2Fthumb_0SFs93BQwFn5k23gDvll.jpg?generation=1631004429577083&alt=media",
        pricePer: 0.99,
        unit: "kg",
        shop: "iki",
        available: true,
    },
    {
        id: "zlyd0ZGFLdmyu8brBFh2",
        name: "Sveriamos bulvės CLEVER, 1 kg",
        categoryId: "sJtx16jajsoTtamdixwy",
        price: 0.79,
        url: "https://lastmile.lt/product/IKI/Sveriamos-bulves-CLEVER-1-kg",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/images%2Fproducts%2Fthumb_zlyd0ZGFLdmyu8brBFh2.jpg?generation=1582208339280093&alt=media",
        pricePer: 0.79,
        unit: "kg",
        shop: "iki",
        available: true,
    },
    {
        id: "jnXBKGWBY34yILGir7A0",
        name: "Lietuviški trumpavaisiai agurkai, 1 kg",
        categoryId: "ofL9nIXiarQ8oBAJeczM",
        price: 4.99,
        url: "https://lastmile.lt/product/IKI/Lietuviski-trumpavaisiai-agurkai-1-kg",
        image: "https://storage.googleapis.com/download/storage/v1/b/lastmile-ui/o/import%2Fphotos%2Fconverted%2Fproduct%2FCvKfTzV4TN5U8BTMF1Hl_jnXBKGWBY34yILGir7A0_xGdb10o0VzY1SFD6eDjbpqgxmW02_U8XC1qeKjJSRoqpPMYD5_thumb.jpg?generation=1645622914782054&alt=media",
        pricePer: 4.99,
        unit: "kg",
        shop: "iki",
        available: true,
    },
];
